language: python
python: 3.5
sudo: false
env:
    - TOX_ENV=py35
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
  global:
    # Because travis runs on Google Cloud and has a /etc/boto.cfg it breaks my
    # dependency on moto in our integration tests.
    # https://github.com/spulec/moto/issues/1771
    # https://github.com/boto/boto/issues/3741
    # This overrides travis and tells it to look nowhere.
    - export BOTO_CONFIG=/dev/null
install:
    - make install
before_script:
    - make moto &
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
matrix:
  include:
    - env:
        - TOX_ENV=upload-download-scripts
      install:
        - make install
        - make run-kinto &
    - env:
        - TOX_ENV=upload-download-scripts
          WITH=kinto-master
      install:
        - make install
        - pip install -U https://github.com/Kinto/kinto/zipball/master
        - make run-kinto &
    - python: 3.6
      env:
        - TOX_ENV=py36
