language: python
python: 3.6
addons:
  postgresql: "9.5"
env:
    - TOX_ENV=py36
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
install:
    - make install
before_script:
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres
    - sudo rm -f /etc/boto.cfg
    - make run-moto &
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
matrix:
  include:
    - env:
        - TOX_ENV=upload-download-scripts
      install:
        - make install
        - make run-kinto &
    - env:
        - TOX_ENV=upload-download-scripts
          WITH=kinto-master
      install:
        - make install
        - pip install -U https://github.com/Kinto/kinto/zipball/master
        - make run-kinto &
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37
