language: python
python: 3.5
env:
    - TOX_ENV=py35
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
install:
    - make install
before_script:
    - sudo rm -f /etc/boto.cfg
    - make moto &
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
matrix:
  include:
    - env:
        - TOX_ENV=upload-download-scripts
      install:
        - make install
        - make run-kinto &
    - env:
        - TOX_ENV=upload-download-scripts
          WITH=kinto-master
      install:
        - make install
        - pip install -U https://github.com/Kinto/kinto/zipball/master
        - make run-kinto &
    - python: 3.6
      env:
        - TOX_ENV=py36
