language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=kinto-master
    - TOX_ENV=upload-download-scripts
    - TOX_ENV=flake8
install:
    - make install
before_script:
    - make moto &
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
