on:
  push:
    branches:
      - master
  pull_request:

name: Unit Testing
jobs:
  chore:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [py38, flake8, kinto-master, upload-download-scripts]
        include:
          - toxenv: py38
            python-version: "3.8"
          - toxenv: flake8
            python-version: "3.X"
          - toxenv: upload-download-scripts
            python-version: "3.X"
          - toxenv: kinto-master
            python-version: "3.X"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install virtualenv
        run: |
          pip install virtualenv
          virtualenv --python=python3 .venv

      - name: Print environment
        run: |
          source .venv/bin/activate
          python --version
          pip --version

      - name: Create database
        env:
          PGPASSWORD: postgres
        run: |
          psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres -h localhost

      - name: Install dependencies
        run: |
          make install

      - name: Run moto
        run: |
          make run-moto

      - name: Run Kinto
        run: |
          make run-kinto

      - name: Tox
        run: |
          source .venv/bin/activate
          tox -e ${{ matrix.toxenv }}

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        if: matrix.toxenv != 'flake8'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage
